### ISSUE TITLE
错误：未能启动监听程序

### ISSUE THREAD

**Issue by yuanzl-1024** [spdir/oracle-single-install#3]
InstallNotice >> Script 2 run ok
InstallNotice >> Oracle start listen ...

正在对命令行参数进行语法分析:
    参数"silent" = true
    参数"responsefile" = /home/oracle/response/netca.rsp
完成对命令行参数进行语法分析。
Oracle Net Services 配置:
完成概要文件配置。
Oracle Net 监听程序启动:
为该监听程序提供的信息正由此计算机上的其他软件使用。
    未能启动监听程序。
有关详细信息, 请查看跟踪文件: /data/app/oracle/cfgtoollogs/netca/trace_OraDB12Home1-1909215下午5137.log
Oracle Net Services 配置失败。退出代码是1
InstallNotice >> Oracle no run listen

**Comment by yuanzl-1024** [comment]
查了下1521端口，也没有被占用呀，系统是Centos 7 64，绝对是全新的，安装包是百度网盘那个，系统在VMware下

**Comment by yuanzl-1024** [comment]
在服务器上试了也不行

[main] [ 2019-09-21 21:57:37.335 CST ] [CmdlineArgs.<init>:154]  Initializing NetProperties...
[main] [ 2019-09-21 21:57:37.348 CST ] [CmdlineArgs.initArgs:171]  Initializing command line arguments...
[main] [ 2019-09-21 21:57:37.363 CST ] [CmdlineArgs.setOraArgs:249]  Setting Oracle arguments...
[main] [ 2019-09-21 21:57:37.364 CST ] [CmdlineArgs.setOraArgs:259]  Read Oracle Home ID =
[main] [ 2019-09-21 21:57:37.554 CST ] [InitialSetup.<init>:4196]  isClientHome: false
[main] [ 2019-09-21 21:57:37.572 CST ] [InitialSetup.configureOPS:4703]  Cluster mode is OFF
[main] [ 2019-09-21 21:57:37.573 CST ] [OPSUtil.getHomeVersion:446]  Inside getHomeVersion...
[main] [ 2019-09-21 21:57:37.891 CST ] [Version.isPre:672]  isPre.java: Returning FALSE
[main] [ 2019-09-21 21:57:37.892 CST ] [Version.isPre:672]  isPre.java: Returning FALSE
[main] [ 2019-09-21 21:57:37.892 CST ] [Version.isPre:672]  isPre.java: Returning FALSE
[main] [ 2019-09-21 21:57:37.892 CST ] [Version.isPre:702]  isPre: Returning FALSE for major version check
[main] [ 2019-09-21 21:57:37.893 CST ] [UnixSystem.isHAConfigured:3579]  olrFileName = /etc/oracle/olr.loc
[main] [ 2019-09-21 21:57:37.923 CST ] [Version.isPre:672]  isPre.java: Returning FALSE
[main] [ 2019-09-21 21:57:37.923 CST ] [Version.isPre:672]  isPre.java: Returning FALSE
[main] [ 2019-09-21 21:57:37.923 CST ] [Version.isPre:672]  isPre.java: Returning FALSE
[main] [ 2019-09-21 21:57:37.924 CST ] [ConfigureListener.isHASRunning:1677]  Is Oracle Restart running: false
        at oracle.net.ca.ConfigureListener.validateEndPoint(ConfigureListener.java:1102)
        at oracle.net.ca.ConfigureListener.typicalConfigure(ConfigureListener.java:279)
        at oracle.net.ca.SilentConfigure.performSilentConfigure(SilentConfigure.java:212)
        at oracle.net.ca.InitialSetup.<init>(NetCA.java:4353)
        at oracle.net.ca.NetCA.main(NetCA.java:452)
        at oracle.net.ca.ConfigureListener.validateEndPoint(ConfigureListener.java:1102)
        at oracle.net.ca.ConfigureListener.typicalConfigure(ConfigureListener.java:279)
        at oracle.net.ca.SilentConfigure.performSilentConfigure(SilentConfigure.java:212)
        at oracle.net.ca.InitialSetup.<init>(NetCA.java:4353)
        at oracle.net.ca.NetCA.main(NetCA.java:452)
        at oracle.net.ca.ConfigureListener.validateEndPoint(ConfigureListener.java:1102)
        at oracle.net.ca.ConfigureListener.typicalConfigure(ConfigureListener.java:279)
        at oracle.net.ca.SilentConfigure.performSilentConfigure(SilentConfigure.java:212)
        at oracle.net.ca.InitialSetup.<init>(NetCA.java:4353)
        at oracle.net.ca.NetCA.main(NetCA.java:452)
        at oracle.net.ca.ConfigureListener.validateEndPoint(ConfigureListener.java:1102)
        at oracle.net.ca.ConfigureListener.typicalConfigure(ConfigureListener.java:279)
        at oracle.net.ca.SilentConfigure.performSilentConfigure(SilentConfigure.java:212)
        at oracle.net.ca.InitialSetup.<init>(NetCA.java:4353)
        at oracle.net.ca.NetCA.main(NetCA.java:452)
        at oracle.net.ca.ConfigureListener.validateEndPoint(ConfigureListener.java:1102)
        at oracle.net.ca.ConfigureListener.typicalConfigure(ConfigureListener.java:279)
        at oracle.net.ca.SilentConfigure.performSilentConfigure(SilentConfigure.java:212)
        at oracle.net.ca.InitialSetup.<init>(NetCA.java:4353)
        at oracle.net.ca.NetCA.main(NetCA.java:452)
        at oracle.net.ca.ConfigureListener.validateEndPoint(ConfigureListener.java:1102)
        at oracle.net.ca.ConfigureListener.typicalConfigure(ConfigureListener.java:279)
        at oracle.net.ca.SilentConfigure.performSilentConfigure(SilentConfigure.java:212)
        at oracle.net.ca.InitialSetup.<init>(NetCA.java:4353)
        at oracle.net.ca.NetCA.main(NetCA.java:452)
        at oracle.net.ca.ConfigureListener.validateEndPoint(ConfigureListener.java:1102)
        at oracle.net.ca.ConfigureListener.typicalConfigure(ConfigureListener.java:279)
        at oracle.net.ca.SilentConfigure.performSilentConfigure(SilentConfigure.java:212)
        at oracle.net.ca.InitialSetup.<init>(NetCA.java:4353)
        at oracle.net.ca.NetCA.main(NetCA.java:452)
        at oracle.net.ca.ConfigureListener.validateEndPoint(ConfigureListener.java:1102)
        at oracle.net.ca.ConfigureListener.typicalConfigure(ConfigureListener.java:279)
        at oracle.net.ca.SilentConfigure.performSilentConfigure(SilentConfigure.java:212)
        at oracle.net.ca.InitialSetup.<init>(NetCA.java:4353)
        at oracle.net.ca.NetCA.main(NetCA.java:452)
        at oracle.net.ca.ConfigureListener.validateEndPoint(ConfigureListener.java:1102)
        at oracle.net.ca.ConfigureListener.typicalConfigure(ConfigureListener.java:279)
        at oracle.net.ca.SilentConfigure.performSilentConfigure(SilentConfigure.java:212)
        at oracle.net.ca.InitialSetup.<init>(NetCA.java:4353)
        at oracle.net.ca.NetCA.main(NetCA.java:452)
        at oracle.net.ca.ConfigureListener.validateEndPoint(ConfigureListener.java:1102)
        at oracle.net.ca.ConfigureListener.typicalConfigure(ConfigureListener.java:279)
        at oracle.net.ca.SilentConfigure.performSilentConfigure(SilentConfigure.java:212)
        at oracle.net.ca.InitialSetup.<init>(NetCA.java:4353)
        at oracle.net.ca.NetCA.main(NetCA.java:452)
        at oracle.net.ca.ConfigureListener.validateEndPoint(ConfigureListener.java:1102)
        at oracle.net.ca.ConfigureListener.typicalConfigure(ConfigureListener.java:279)
        at oracle.net.ca.SilentConfigure.performSilentConfigure(SilentConfigure.java:212)
        at oracle.net.ca.InitialSetup.<init>(NetCA.java:4353)
        at oracle.net.ca.NetCA.main(NetCA.java:452)
        at oracle.net.ca.ConfigureListener.validateEndPoint(ConfigureListener.java:1102)
        at oracle.net.ca.ConfigureListener.typicalConfigure(ConfigureListener.java:279)
        at oracle.net.ca.SilentConfigure.performSilentConfigure(SilentConfigure.java:212)
        at oracle.net.ca.InitialSetup.<init>(NetCA.java:4353)
        at oracle.net.ca.NetCA.main(NetCA.java:452)
        at oracle.net.ca.ConfigureListener.validateEndPoint(ConfigureListener.java:1102)
        at oracle.net.ca.ConfigureListener.typicalConfigure(ConfigureListener.java:279)
        at oracle.net.ca.SilentConfigure.performSilentConfigure(SilentConfigure.java:212)
        at oracle.net.ca.InitialSetup.<init>(NetCA.java:4353)
        at oracle.net.ca.NetCA.main(NetCA.java:452)
        at oracle.net.ca.ConfigureListener.validateEndPoint(ConfigureListener.java:1102)
        at oracle.net.ca.ConfigureListener.typicalConfigure(ConfigureListener.java:279)
        at oracle.net.ca.SilentConfigure.performSilentConfigure(SilentConfigure.java:212)
        at oracle.net.ca.InitialSetup.<init>(NetCA.java:4353)
        at oracle.net.ca.NetCA.main(NetCA.java:452)
        at oracle.net.ca.ConfigureListener.validateEndPoint(ConfigureListener.java:1102)
        at oracle.net.ca.ConfigureListener.typicalConfigure(ConfigureListener.java:279)
        at oracle.net.ca.SilentConfigure.performSilentConfigure(SilentConfigure.java:212)
        at oracle.net.ca.InitialSetup.<init>(NetCA.java:4353)
        at oracle.net.ca.NetCA.main(NetCA.java:452)
        at oracle.net.ca.ConfigureListener.validateEndPoint(ConfigureListener.java:1102)
        at oracle.net.ca.ConfigureListener.typicalConfigure(ConfigureListener.java:279)
        at oracle.net.ca.SilentConfigure.performSilentConfigure(SilentConfigure.java:212)
        at oracle.net.ca.InitialSetup.<init>(NetCA.java:4353)
        at oracle.net.ca.NetCA.main(NetCA.java:452)
        at oracle.net.ca.NetCA.main(NetCA.java:452)
[main] [ 2019-09-21 21:57:38.420 CST ] [ConfigureListener.typicalConfigure:283]  The information provided for this listener is currently in use by other software on this computer.
[main] [ 2019-09-21 21:57:38.420 CST ] [ConfigureListener.validateEndPoint:1074]  Validating end-point: TCP:1538
oracle.net.ca.IllegalEndpointException: The information provided for this listener is currently in use by other software on this computer.
        at oracle.net.ca.ConfigureListener.validateEndPoint(ConfigureListener.java:1102)
        at oracle.net.ca.ConfigureListener.typicalConfigure(ConfigureListener.java:279)
        at oracle.net.ca.SilentConfigure.performSilentConfigure(SilentConfigure.java:212)
        at oracle.net.ca.InitialSetup.<init>(NetCA.java:4353)
        at oracle.net.ca.NetCA.main(NetCA.java:452)
[main] [ 2019-09-21 21:57:38.424 CST ] [ConfigureListener.typicalConfigure:283]  The information provided for this listener is currently in use by other software on this computer.
[main] [ 2019-09-21 21:57:38.424 CST ] [ConfigureListener.validateEndPoint:1074]  Validating end-point: TCP:1539
oracle.net.ca.IllegalEndpointException: The information provided for this listener is currently in use by other software on this computer.
        at oracle.net.ca.ConfigureListener.validateEndPoint(ConfigureListener.java:1102)
        at oracle.net.ca.ConfigureListener.typicalConfigure(ConfigureListener.java:279)
        at oracle.net.ca.SilentConfigure.performSilentConfigure(SilentConfigure.java:212)
        at oracle.net.ca.InitialSetup.<init>(NetCA.java:4353)
        at oracle.net.ca.NetCA.main(NetCA.java:452)
[main] [ 2019-09-21 21:57:38.430 CST ] [ConfigureListener.typicalConfigure:283]  The information provided for this listener is currently in use by other software on this computer.
[main] [ 2019-09-21 21:57:38.430 CST ] [ConfigureListener.typicalConfigure:298]  Failed to get free port. Using port 1521.

**Comment by wsad137** [comment]
需要保证 ping hostname 返回本机ip 不是127.0.0.1
